### ISSUE TITLE
在windows-x86环境下无法成功激活

### ISSUE THREAD

**Issue by kevin100702** [colin-chang/ArcFace.Net#16]
经确认Appid等设置是正确的，但是在运行激活的时候提示无法激活，返回的code的位数也异常，不是通常的5位，具体错误信息如下图

```[10:08:12 FTL] Application terminated unexpectedly
System.AggregateException: One or more errors occurred. (failed to active. error code:2982913301706530818. please try again)
 ---> System.Exception: failed to active. error code:2982913301706530818. please try again
   at ColinChang.ArcFace.Core.ArcFace.<>c__DisplayClass48_0.<<OnlineActiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ColinChang.ArcFace.Core.ArcFace.OnlineActiveAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ColinChang.ArcFace.Core.ArcFace..ctor(IImageProcessor processor, ArcFaceOptions options)
   at ColinChang.ArcFace.Core.ArcFace..ctor(IImageProcessor processor, IOptionsMonitor`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)```

**Comment by colin-chang** [comment]
我同事也遇到了无法激活的问题，联系虹软客服回复说是免费版要在每天指定时间段才能激活，具体时段忘记了，好想是说下午14点到几点来着，具体可以尝试联系下虹软客服
